version: "3.3"
services:
  elasticsearch:
    image: wwqq/elastic:1.0
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:5.4.0
  #   container_name: kibana_540
  #   environment:
  #     - SERVER_HOST=0.0.0.0
  #   volumes:
  #     - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  #   ports:
  #     - 5601:5601
  # headPlugin:
  #   image: mobz/elasticsearch-head:5
  #   container_name: head_540
  #   ports:
  #     - 9100:9100